### These are the default dovecot settings, comments and all
# dovecot.conf
default['dovecot']['config_dir'] = "/etc/dovecot"
default['dovecot']['config'] = "dovecot.conf"
default['dovecot']['protocols'] = "none"
default['dovecot']['log_timestamp'] = "%Y-%m-%d %H:%M:%S"
default['dovecot']['mail_privileged_group'] = "mail"
default['dovecot']['pop3_uidl_format'] = "%08Xu%08Xv"
default['dovecot']['auth_default_mechanisms'] = "plain"
default['dovecot']['auth_user'] = "root"
default['dovecot']['protocols_example'] = [ "imap","imaps" ]
default['dovecot']['db_example_config'] = "dovecot-db-example.conf"
#default['dovecot']['base_dir'] = "/var/run/dovecot"
#default['dovecot']['imap_listen'] = "*:10143"
#default['dovecot']['ssl_imap_listen'] = "*:10943"
#default['dovecot']['pop3_listen'] = "*:10100"
#default['dovecot']['managesieve_listen'] = "*:12000"
#default['dovecot']['listen'] = "*"
#default['dovecot']['disable_plaintext_auth'] = "yes"
#default['dovecot']['shutdown_clients'] = "yes"
#default['dovecot']['log_path'] = ""
#default['dovecot']['info_log_path'] = ""
#default['dovecot']['syslog_facility'] = "mail"
#default['dovecot']['ssl_listen'] = ""
#default['dovecot']['ssl'] = "yes"
#default['dovecot']['ssl_cert_file'] = "/etc/ssl/certs/dovecot.pem"
#default['dovecot']['ssl_key_file'] = "/etc/ssl/private/dovecot.pem"
#default['dovecot']['ssl_key_password'] = ""
#default['dovecot']['ssl_ca_file'] = ""
#default['dovecot']['ssl_verify_client_cert'] = "no"
#default['dovecot']['ssl_username_from_cert'] = "yes."
#default['dovecot']['ssl_cert_username_field'] = "commonName"
#default['dovecot']['ssl_parameters_regenerate'] = "168"
#default['dovecot']['ssl_cipher_list'] = "ALL:!LOW:!SSLv2"
#default['dovecot']['verbose_ssl'] = "no"
#default['dovecot']['login_dir'] = "/var/run/dovecot/login"
#default['dovecot']['login_chroot'] = "yes"
#default['dovecot']['login_user'] = "dovecot"
#default['dovecot']['login_process_size'] = "64"
#default['dovecot']['login_process_per_connection'] = "yes"
#default['dovecot']['login_processes_count'] = "3"
#default['dovecot']['login_max_processes_count'] = "128"
#default['dovecot']['login_max_connections'] = "256"
#default['dovecot']['login_greeting'] = "dovecot ready."
#default['dovecot']['login_trusted_networks'] = ""
#default['dovecot']['login_log_format_elements'] = "user=<%u> method=%m rip=%r lip=%l %c"
#default['dovecot']['login_log_format'] = "%$:%s"
#default['dovecot']['mail_location_example1'] = "maildir:~/Maildir"
#default['dovecot']['mail_location_example2'] = "mbox:~/mail:INBOX=/var/mail/%u"
#default['dovecot']['mail_location_example3'] = "mbox:/var/mail/%d/%1n/%n:INDEX=/var/indexes/%d/%1n/%n"
#default['dovecot']['mail_location'] = ""
#default['dovecot']['private_private'] = ""
#default['dovecot']['private_separator'] = ""
#default['dovecot']['private_location'] = ""
#default['dovecot']['private_inbox'] = "no"
#default['dovecot']['private_hidden'] = "yes"
#default['dovecot']['private_list'] = "yes"
#default['dovecot']['private_subscriptions'] = "yes"
#default['dovecot']['shared_separator'] = "/"
#default['dovecot']['shared_prefix'] = "shared/%%u/"
#default['dovecot']['shared_location'] = "maildir:%%h/Maildir:INDEX=~/Maildir/shared/%%u"
#default['dovecot']['shared_subscriptions'] = "no"
#default['dovecot']['shared_list'] = "children"
#default['dovecot']['mail_uid'] = ""
#default['dovecot']['mail_gid'] = ""
#default['dovecot']['mail_access_groups'] = ""
#default['dovecot']['mail_full_filesystem_access'] = "no"
#default['dovecot']['mail_debug'] = "no"
#default['dovecot']['mail_log_prefix'] = ""%Us(%u):""
#default['dovecot'][''] = ""
#default['dovecot']['mail_log_max_lines_per_sec'] = "10"
#default['dovecot']['mmap_disable'] = "no"
#default['dovecot']['dotlock_use_excl'] = "yes"
#default['dovecot']['fsync_disable'] = "no"
#default['dovecot']['mail_nfs_storage'] = "no"
#default['dovecot']['mail_nfs_index'] = "no"
#default['dovecot']['lock_method'] = "fcntl"
#default['dovecot']['mail_drop_priv_before_exec'] = "no"
#default['dovecot']['verbose_proctitle'] = "no"
#default['dovecot']['first_valid_uid'] = "500"
#default['dovecot']['last_valid_uid'] = "0"
#default['dovecot']['first_valid_gid'] = "1"
#default['dovecot']['last_valid_gid'] = "0"
#default['dovecot']['max_mail_processes'] = "512"
#default['dovecot']['mail_process_size'] = "256"
#default['dovecot']['mail_max_keyword_length'] = "50"
#default['dovecot']['valid_chroot_dirs'] = ""
#default['dovecot']['mail_chroot'] = ""
#default['dovecot']['mail_cache_min_mail_count'] = "0"
#default['dovecot']['mailbox_idle_check_interval'] = "30"
#default['dovecot']['mail_save_crlf'] = "no"
#default['dovecot']['maildir_stat_dirs'] = "no"
#default['dovecot']['maildir_copy_with_hardlinks'] = "yes"
#default['dovecot']['maildir_copy_preserve_filename'] = "no"
#default['dovecot']['maildir_very_dirty_syncs'] = "no"
#default['dovecot']['dovecot'] = "dotlock fcntl"
#default['dovecot']['Debian'] = "fcntl dotlock"
#default['dovecot']['mbox_read_locks'] = "fcntl"
#default['dovecot']['mbox_write_locks'] = "fcntl dotlock"
#default['dovecot']['mbox_lock_timeout'] = "300"
#default['dovecot']['mbox_dotlock_change_timeout'] = "120"
#default['dovecot']['mbox_dirty_syncs'] = "yes"
#default['dovecot']['mbox_very_dirty_syncs'] = "no"
#default['dovecot']['mbox_lazy_writes'] = "yes"
#default['dovecot']['mbox_min_index_size'] = "0"
#default['dovecot']['dbox_rotate_size'] = "2048"
#default['dovecot']['dbox_rotate_min_size'] = "16"
#default['dovecot']['midnight'] = "today, 2 = yesterday, etc. 0 = check disabled."
#default['dovecot']['dbox_rotate_days'] = "0"
#default['dovecot']['imap_login_executable'] = "/usr/lib/dovecot/imap-login"
#default['dovecot']['imap_mail_executable_example'] = "/usr/lib/dovecot/rawlog /usr/lib/dovecot/imap"
#default['dovecot']['imap_mail_executable'] = "/usr/lib/dovecot/gdbhelper /usr/lib/dovecot/imap"
#default['dovecot']['imap_mail_executable'] = "/usr/lib/dovecot/imap"
#default['dovecot']['imap_max_line_length'] = "65536"
#default['dovecot']['imap_mail_max_userip_connections'] = "10"
#default['dovecot']['imap_mail_plugins'] = ""
#default['dovecot']['imap_mail_plugin_dir'] = "/usr/lib/dovecot/modules/imap"
#default['dovecot']['imap_logout_format'] = "bytes=%i/%o"
#default['dovecot']['imap_capability'] = ""
#default['dovecot']['imap_idle_notify_interval'] = "120"
#default['dovecot']['imap_id_send'] = ""
#default['dovecot']['imap_id_log'] = ""
#default['dovecot']['imap_client_workarounds'] = ""
#default['dovecot']['pop3_login_executable'] = "/usr/lib/dovecot/pop3-login"
#default['dovecot']['pop3_mail_executable'] = "/usr/lib/dovecot/pop3"
#default['dovecot']['pop3_no_flag_updates'] = "no"
#default['dovecot']['pop3_enable_last'] = "no"
#default['dovecot']['pop3_reuse_xuidl'] = "no"
#default['dovecot']['pop3_lock_session'] = "no"
#default['dovecot']['pop3_save_uidl'] = "no"
#default['dovecot']['pop3_logout_format'] = "top=%t/%p, retr=%r/%b, del=%d/%m, size=%s"
#default['dovecot']['pop3_mail_max_userip_connections'] = "3"
#default['dovecot']['pop3_mail_plugins'] = ""
#default['dovecot']['pop3_mail_plugin_dir'] = "/usr/lib/dovecot/modules/popdefault['dovecot']['pop3_mail_plugins'] = "'3"
#default['dovecot']['pop3_client_workarounds'] = ""
#default['dovecot']['managesieve_login_executable'] = "/usr/lib/dovecot/managesieve-login"
#default['dovecot']['managesieve_mail_executable'] = "/usr/lib/dovecot/managesieve"
#default['dovecot']['managesieve_max_line_length'] = "65536"
#default['dovecot']['managesieve_logout_format'] = "bytes=%i/%o"
#default['dovecot']['managesieve_mail_location'] = "mbox:~/mail"
#default['dovecot']['managesieve_implementation_string'] = "Cyrus timsieved v2.2.13"
#default['dovecot']['lda_postmaster_address'] = ""
#default['dovecot']['lda_hostname'] = ""
#default['dovecot']['lda_mail_plugins'] = ""
#default['dovecot']['lda_mail_plugin_dir'] = "/usr/lib/dovecot/modules/lddefault['dovecot']['lda_mail_plugins'] = "'a"
#default['dovecot']['lda_quota_full_tempfail'] = "no"
#default['dovecot']['lda_deliver_log_format'] = "msgid=%m:%$"
#default['dovecot']['lda_sendmail_path'] = "/usr/sbin/sendmail"
#default['dovecot']['lda_rejection_subject'] = "Rejected:%s"
#default['dovecot']['lda_auth_socket_path'] = "/var/run/dovecot/auth-master"
#default['dovecot']['auth_executable'] = "/usr/lib/dovecot/dovecot-auth"
#default['dovecot']['auth_process_size'] = "256"
#default['dovecot']['auth_cache_size'] = "0"
#default['dovecot']['auth_cache_ttl'] = "3600"
#default['dovecot']['auth_cache_negative_ttl'] = "3600"
#default['dovecot']['auth_realms'] = ""
#default['dovecot']['auth_default_realm'] = ""
#default['dovecot']['auth_username_chars'] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@"
#default['dovecot']['auth_username_translation'] = ""
#default['dovecot']['auth_username_format'] = ""
#default['dovecot']['auth_master_user_separator'] = ""
#default['dovecot']['auth_anonymous_username'] = "anonymous"
#default['dovecot']['auth_verbose'] = "no"
#default['dovecot']['auth_debug'] = "no"
#default['dovecot']['auth_debug_passwords'] = "no"
#default['dovecot']['auth_worker_max_count'] = "30"
#default['dovecot']['auth_gssapi_hostname'] = ""
#default['dovecot']['auth_krb5_keytab'] = ""
#default['dovecot']['auth_use_winbind'] = "no"
#default['dovecot']['auth_winbind_helper_path'] = "/usr/bin/ntlm_auth"
#default['dovecot']['auth_failure_delay'] = "2"
#default['dovecot']['auth_passdb_args'] = "/etc/dovecot/dovecot.deny"
#default['dovecot']['auth_passdb_deny'] = "yes"
#default['dovecot']['auth_passdb_args_example1'] = "session=yes %Ls"
#default['dovecot']['auth_passdb_args_example2'] = "cache_key=%u dovecot"
#default['dovecot']['auth_passdb_args'] = "dovecot"
#default['dovecot']['passdb_passwd_args'] = ""
#default['dovecot']['passdb_shadow_args'] = ""
#default['dovecot']['passdb_bsdauth_args'] = ""
#default['dovecot']['passdb_passwd_file_args'] = ""
#default['dovecot']['passdb_checkpassword_args'] = ""
#default['dovecot']['passdb_sql_args'] = "/etc/dovecot/dovecot-sql.conf"
#default['dovecot']['passdb_ldap_args'] = "/etc/dovecot/dovecot-ldap.conf"
#default['dovecot']['passdb_vpopmail_args'] = ""
#default['dovecot']['userdb_passwd_args'] = ""
#default['dovecot']['userdb_passwd_file_args'] = ""
#default['dovecot']['userdb_checkpassword_args'] = ""
#default['dovecot']['userdb_static_args'] = "uid=500 gid=500 home=/var/mail/%u"
#default['dovecot']['userdb_static_args'] = ""
#default['dovecot']['userdb_sql_args'] = "/etc/dovecot/dovecot-sql.conf"
#default['dovecot']['userdb_ldap_args'] = "/etc/dovecot/dovecot-ldap.conf"
#default['dovecot']['chroot'] = ""
#default['dovecot']['count'] = "1"
#default['dovecot']['ssl_require_client_cert'] = "no"
#default['dovecot']['ssl_username_from_cert'] = "no"
#default['dovecot']['socket_listen_master_path'] = "path/var/run/dovecot/auth-master"
#default['dovecot']['socket_listen_master_mode'] = "0600"
#default['dovecot']['socket_listen_master_user'] = ""
#default['dovecot']['socket_listen_master_group'] = ""
#default['dovecot']['socket_listen_client_path'] = "path/var/run/dovecot/auth-client"
#default['dovecot']['socket_listen_client_mode'] = "0660"
#default['dovecot']['auth_external_socket_connect_master_path'] = "/var/run/dovecot/auth-master"
#default['dovecot']['dict_quota'] = "mysql:/etc/dovecot/dovecot-dict-quota.conf"
#default['dovecot']['dict_expire'] = "db:/var/lib/dovecot/expire.db"
#default['dovecot']['dict_db_config'] = ""
#default['dovecot']['quota_rule_example1'] = "*:storage=1048576"
#default['dovecot']['quota_rule2_example1'] = "Trash:storage=102400"
#default['dovecot']['quota_example'] = "dict:user::proxy::quota"
#default['dovecot']['quota2_example'] = "dict:domain:%d:proxy::quota_domain"
#default['dovecot']['quota_rule_example2'] = "*:storage=102400"
#default['dovecot']['quota2_rule_example2'] = "*:storage=1048576"
#default['dovecot']['plugin_quota_warning'] = "storage=95%% /usr/local/bin/quota-warning.sh 95"
#default['dovecot']['plugin_quota_warning2'] = "storage=80%% /usr/local/bin/quota-warning.sh 80"
#default['dovecot']['plugin_quota'] = "maildir"
#default['dovecot']['acl'] = "vfile:/etc/dovecot/dovecot-acls:cache_secs=300"
#default['dovecot']['acl_shared_dict'] = "file:/var/lib/dovecot/shared-mailboxes"
#default['dovecot']['convert_mail'] = "mbox:%h/mail"
#default['dovecot']['convert_skip_broken_mailboxes'] = "no"
#default['dovecot']['convert_skip_dotdirs'] = "no"
#default['dovecot']['convert_alt_hierarchy_char'] = "_"
#default['dovecot']['trash'] = "/etc/dovecot/dovecot-trash.conf"
#default['dovecot']['expire'] = "Trash 7 Spam 30"
#default['dovecot']['expire_dict'] = "proxy::expire"
#default['dovecot']['lazy_expunge'] = ".EXPUNGED/ .DELETED/ .DELETED/.EXPUNGED/"
#default['dovecot']['mail_log_events'] = "delete undelete expunge copy mailbox_delete mailbox_rename"
#default['dovecot']['mail_log_group_events'] = "no"
#default['dovecot']['mail_log_fields'] = "uid box msgid size"
#default['dovecot']['sieve'] = "dovecot.sieve"
#default['dovecot']['sieve_dir'] = "sieve"
#default['dovecot']['include'] = "/etc/dovecot/conf.d/*.conf"
#default['dovecot']['include_try'] = "/etc/dovecot/conf.d/extra.conf"

# dovecot-db-example.conf
default['dovecot']['set_tx_max'] = "1000"
#default['dovecot']['set_lk_max_locks "] = "1000"
#default['dovecot']['set_lk_max_lockers "] = "1000"
#default['dovecot']['set_lk_max_objects "] = "1000"

# dovecot-dict-sql-example.conf
default['dovecot']['dict_sql_example_config'] = "dovecot-dict-sql-example.conf"
default['dovecot']['sql_config'] = "dovecot-sql.conf"
default['dovecot']['pattern1'] = "priv/quota/storage"
default['dovecot']['pattern2'] = "shared/expire/$user/$mailbox"
default['dovecot']['table1'] = "quota"
default['dovecot']['table2'] = "expires"
default['dovecot']['value_field1'] = "bytes"
default['dovecot']['value_field2'] = "messages"
default['dovecot']['value_field3'] = "expire_stamp"
default['dovecot']['fields_username'] = "username"
default['dovecot']['fields_mailbox'] = "$mailbox"
#default['dovecot']['host'] = "localhost"
#default['dovecot']['dbname'] = "mails"
#default['dovecot']['user'] = "testuser"
#default['dovecot']['password'] = "pass"

# dovecot-ldap.conf
default['dovecot']['base'] = ""
default['dovecot']['ldap_config'] = "dovecot-ldap.conf"
#default['dovecot']['hosts'] = ""
#default['dovecot']['uris'] = ""
#default['dovecot']['dn'] = "yes"
#default['dovecot']['dnpass'] = ""
#default['dovecot']['sasl_bind'] = "no"
#default['dovecot']['sasl_mech'] = ""
#default['dovecot']['sasl_realm'] = ""
#default['dovecot']['sasl_authz_id'] = ""
#default['dovecot']['tls'] = "no"
#default['dovecot']['tls_ca_cert_file'] = ""
#default['dovecot']['tls_ca_cert_dir'] = ""
#default['dovecot']['tls_cert_file'] = ""
#default['dovecot']['tls_key_file'] = ""
#default['dovecot']['tls_cipher_suite'] = ""
#default['dovecot']['tls_require_cert'] = ""
#default['dovecot']['ldaprc_path'] = ""
#default['dovecot']['debug_level'] = "0"
#default['dovecot']['auth_bind'] = "no"
#default['dovecot']['auth_bind_userdn'] = ""
#default['dovecot']['ldap_version'] = "3"
#default['dovecot']['deref'] = "never"
#default['dovecot']['scope'] = "subtree"
#default['dovecot']['user_attrs'] = "homeDirectory=home,uidNumber=uid,gidNumber=gid"
#default['dovecot']['user_filter'] = "(&(objectClass=posixAccount)(uid=%u))"
#default['dovecot']['pass_attrs'] = "uid=user,userPassword=password"
#default['dovecot']['pass_attrs'] = "uid=user,userPassword=password,\"
#default['dovecot']['homeDirectory'] = "userdb_home,uidNumber=userdb_uid,gidNumber=userdb_gid"
#default['dovecot']['pass_filter'] = "(&(objectClass=posixAccount)(uid=%u))"
#default['dovecot']['default_pass_scheme'] = "CRYPT"

# dovecot-sql.conf
#default['dovecot']['driver'] = ""
#default['dovecot']['connect'] = ""
#default['dovecot']['default_pass_scheme'] = "MD5"
#default['dovecot']['password_query1'] = "SELECT username, domain, password "
#default['dovecot']['password_query1'] <<  "FROM users WHERE username = "%n' AND domain = "%d'"
#default['dovecot']['user_query'] = "SELECT home, uid, gid "
#default['dovecot']['user_query'] << "FROM users WHERE username = "%n' AND domain = "%d'"
#default['dovecot']['password_query2'] = "SELECT userid AS user, password, "
#default['dovecot']['password_query2'] << "home AS userdb_home, uid AS userdb_uid, gid AS userdb_gid "
#default['dovecot']['password_query2'] << "FROM users WHERE userid = "%u'"
